import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'Japan-China Insights | 24/7 Intel Dashboard',
  description: 'AI-Powered Insights on Japanese Politics, Economics, and Sino-Japanese Relations. Generated by Antigravity.',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
